
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepulse-backend
  labels:
    app: kubepulse-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubepulse-backend
  template:
    metadata:
      labels:
        app: kubepulse-backend
    spec:
      containers:
      - name: backend
        image: javisanz23/kubepulse-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: redis-password
