apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepulse-frontend
  labels:
    app: kubepulse-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubepulse-frontend
  template:
    metadata:
      labels:
        app: kubepulse-frontend
    spec:
      containers:
      - name: frontend
        image: javisanz23/kubepulse-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
