name: 🚀 KubePulse CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # Se dispara solo cuando subes cambios a la rama main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el código del repositorio en la máquina virtual de GitHub
    - name: ⬇️ Checkout code
      uses: actions/checkout@v4

    # 2. Iniciar sesión en Docker Hub usando los secretos que configuramos
    - name: 🔐 Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets::DOCKERHUB_USERNAME }}
        password: ${{ secrets::DOCKERHUB_TOKEN }}

    # 3. Construir y subir la imagen del Backend
    - name: 📦 Build and Push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./app/backend
        push: true
        tags: ${{ secrets::DOCKERHUB_USERNAME }}/kubepulse-backend:latest

    # 4. Construir y subir la imagen del Frontend
    - name: 📦 Build and Push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./app/frontend
        push: true
        tags: ${{ secrets::DOCKERHUB_USERNAME }}/kubepulse-frontend:latest
